FROM mcr.microsoft.com/mssql/server:2019-latest

USER root

RUN mkdir -p /usr/config

# Copia y da permisos como root
COPY . /usr/config
RUN chmod +x /usr/config/entrypoint.sh \
    && chown -R mssql /usr/config

USER mssql

WORKDIR /usr/config

ENTRYPOINT ["./entrypoint.sh"]

